version: '3'

services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "./UserService:/app"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: entrance-user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: localhost
    volumes:
      - "/var/docker-db-lab:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: app
    restart: always
    volumes:
      - "./UserService:/app"
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "127.0.0.1:80:80"

volumes:
  pg_data:

networks:
  my_network:
